ANSWERS = [
    "CHMOD", "CHOWN", "CHGRP", "MKDIR", "RMDIR", "TOUCH", "SHRED", "PASTE",
    "SPLIT", "PATCH", "XARGS", "WATCH", "SLEEP", "UNZIP", "MKNOD",
    "MOUNT", "FDISK", "GDISK", "BLKID", "LSBLK", "BTRFS",
    "PKILL", "UNAME", "WHICH", "ALIAS", "CLEAR", "RESET", "FUSER", "USERS",
    "LOGIN", "UMASK", "CHAGE", "NOHUP", "DMESG", "LSMOD", "LSPCI", "LSUSB",
    "NGINX", "HTTPD", "CROND", "RSYNC", "NMCLI", "IPSET", "ROUTE", "WHOIS",
    "IFTOP", "NLOAD", "IPERF",
    "CMAKE", "CLANG", "JAVAC", "RUSTC", "CARGO", "BLACK", "ISORT", "SWIFT",
    "BABEL", "RAILS", "FLASK", "SCONS", "CTAGS", "EMACS", "CABAL", "STACK",
    "NINJA",
    "MYSQL", "MONGO", "VAULT", "NOMAD", "BYOBU",
    "FALSE", "UNSET", "LOCAL", "SHIFT", "BREAK", "UNTIL",
]
